spring:
  application:
    name: business-register-service
  main:
    allow-bean-definition-overriding: true
  # 格式化日期时间
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  #配置注册nacos地址
  cloud:
    nacos:
      discovery:
        server-addr: nacos.sen.com:80

dubbo:
  scan:
    base-packages: com.sen.myshop.plus.business
  protocol:
    name: dubbo
    port: -1
    serialization: kryo
  registry:
    address: nacos://nacos.sen.com
    port: 80

server:
  # ${random.int[9000,9999]} 9000-9999随机端口
  port: 9000


management:
  endpoints:
    web:
      exposure:
        include: "*"